/*
 * Created by SharpDevelop.
 * Date: 22/09/2020
 * SavanDev - MIT License
*/
using System;
using System.Collections.Generic;
using System.Text;

namespace FloatFolder
{
	public class App
	{
		List<Shortcut> shortcuts;
		
		public App()
		{
			shortcuts = new List<Shortcut>();
		}
		
		public void AddShortcut(string name, string url)
		{
			shortcuts.Add(new Shortcut(name, url));
		}
		
		public void RemoveShortcut(int index)
		{
			shortcuts.RemoveAt(index);
		}
		
		public void ClearShortcuts()
		{
			shortcuts.Clear();
		}
		
		public string GenerateApp()
		{
			StringBuilder code = new StringBuilder();
			
			// Referencias
			code.AppendLine(Template.AppNamespace).AppendLine();
			
			// Assembly options
			code.AppendLine("[assembly: AssemblyVersion(\"1.0.*\")]");
			code.AppendLine("[assembly: AssemblyProduct(\"FloatFolder\")]");
			code.AppendLine("[assembly: AssemblyTitle(\"Folder generated by FloatFolder!\")]");
			code.AppendLine("[assembly: AssemblyCompany(\"" + Environment.UserName + "\")]").AppendLine();
			
			// Código
			code.AppendLine("namespace SavanDev {");
			code.AppendLine(Template.AppProgram).AppendLine();
			
			StringBuilder codeShortcut = new StringBuilder();
			foreach (var item in shortcuts) {
				codeShortcut.AppendLine("Nombre.Add(\"" + item.name + "\");");
				codeShortcut.AppendLine("Url.Add(\"" + item.url.Replace("\\", "\\\\") + "\");");
			}
			
			code.AppendLine(Template.AppMain(codeShortcut.ToString()));
			code.AppendLine("}").AppendLine();
			
			return code.ToString();
		}
	}
	
	public class Shortcut
	{
		public string name;
		public string url;
		
		public Shortcut(string _name, string _url)
		{
			name = _name;
			url = _url;
		}
	}
}